FROM node:16-alpine
EXPOSE 3000
WORKDIR /Expense-Tracker
COPY Frontend/package.json .
COPY Frontend/package-lock.json .
RUN npm install
RUN npm install react-scripts 

COPY Frontend/ .
CMD [ "npm","start"]
